### ISSUE TITLE
geostats.getClassJenks (and perhaps others) return non-numeric breaks.

### ISSUE THREAD

**Issue by JoshMcCullough** [simogeo/geostats#21]
var values = [43.96, 50.92, 45.96, 45.44, 44.95, 46.64, 44.16, 45.63, 40.4, 45.16, 44.21, 46.27, 47.93, 44.77, 45.1, 45.94, 45.53, 44.79, 44.84, 45.84, 44.22, 44.55, 45.35, 45.8, 43.67, 45.17, 47.88, 45.07, 47.95, 46.26, 44.07, 47.07, 43.73, 44.33, 46.88, 44.66, 45.16, 46.05, 44.43, 43.9, 43.33, 44.8, 47.24, 44.88, 45.43, 46.89, 46.37, 44.67, 46.62, 46.43, 45.8, 47.05];
    var gs = new geostats(values);
    var breaks = gs.getClassJenks(5);

*Results:*

    [40.4, "43.33", "44.95", "46.27", "47.95", 50.92]

*Expected:*

    [40.4, 43.33, 44.95, 46.27, 47.95, 50.92]

**Comment by simogeo** [comment]
Are you sure ? I've made a test on the serie you proposed : see http://jsfiddle.net/ro91wju0/

**Comment by simogeo** [comment]
any news regarding this ?

**Comment by JoshMcCullough** [comment]
I was sure, but will double check this next week.

**Comment by simogeo** [comment]
@JoshMcCullough : this bug has been fixed some months ago. see https://github.com/simogeo/geostats/commit/ecb499f7b5272a2570f72f689f7e873f7ebcc092

**Comment by JoshMcCullough** [comment]
Yes, it does appear to be fixed in the latest version. Thanks.
