### ISSUE TITLE
"geostats" class name should be CamelCase.

### ISSUE THREAD

**Issue by JoshMcCullough** [simogeo/geostats#23]
Following standard JS conventions, class names should be CamelCase: `Geostats` or `GeoStats`

There is some unexpected issue if you, like me, tend to name instances like this after the class which they represent:

```
var geostats = new geostats(values);
```

`geostats` is redefined here, so you end up with a somewhat non-obvious JS error.

**Comment by simogeo** [comment]
javascript is not really an object oriented language and I don't know what *standard convention* you're referring about. May you point to some link ?

Most of all, changing this right now would completely break the current library compatibility ...

**Comment by JoshMcCullough** [comment]
I know it seems nitpicky but it got me for a while. General convention is similar to the general conventions used in Java. See [Google's Style Guide for JS](http://google-styleguide.googlecode.com/svn/trunk/javascriptguide.xml#Naming), for example.

I know it's a breaking change and not one you're likely to make, but I thought it was worth pointing out. I'd be surprised if I was the first person who ran into this problem!
