### ISSUE TITLE
getClassStdDeviation with negative values

### ISSUE THREAD

**Issue by frankjar** [simogeo/geostats#27]
the StDeviation() method doesn't fix the min and the max value correctly.
This method can compute bounds larger than the min/max values.

Here are my corrections :

       // we finally set the first value
    	// a[0] = this.min();
        a[0] = a[1]-this.stddev();
    	
    	// we finally set the last value
    	// a[nbClass] = this.max();
        a[nbClass] = a[nbClass-1]+this.stddev();

**Comment by simogeo** [comment]
Thanks, but I guess this can be optional. What do you think ?

     // we finally set the first value
     // do we excatly match min value or not ? 
     a[0] = (typeof matchBounds === "undefined") ? a[1]-this.stddev() : this.min();
    	
     // we finally set the last value
     // do we excatly match max value or not ? 
     a[nbClass] = (typeof matchBounds === "undefined") ? a[nbClass-1]+this.stddev() : this.max();

with `matchBounds` as optional parameter when calling the method.

**Comment by simogeo** [comment]
By the way, it seems qgis for example just return min and max values.

**Comment by frankjar** [comment]
your solution is better, i will use it. Mine was only to inform.
thx !

**Comment by simogeo** [comment]
Fixed : d38671f4993aa7e5ea8e6d966a55380c69d8bbd6
