### ISSUE TITLE
NPM install out of date

### ISSUE THREAD

**Issue by stevage** [simogeo/geostats#28]
Geostats on NPM is version 1.1.0. `require('geostats')` seems to yield an object and not work at all.

The workaround, `npm install simogeo/geostats` works, but is a workaround and others might fall into this trap.

**Comment by simogeo** [comment]
Thanks for reporting. 
I'm not very familiar with NPM. I just checked my package.jso file syntax and it is valid ...

Do you know what to do to make this work with require() command ?

**Comment by stevage** [comment]
I think you just need to [publish](https://docs.npmjs.com/cli/publish) the more recent version?

(To clarify, the "`require`" problem was only a problem with 1.1.0 - the current version in Github works fine for me.)

**Comment by simogeo** [comment]
ok, thanks to you. It should be ok right now !
