### ISSUE TITLE
Statistics are not reset after setSerie

### ISSUE THREAD

**Issue by daniel-zillion** [simogeo/geostats#29]
When the serie is updated with setSerie, the statistic fields (this.stat_*) are not reset, which causes other functions like getClassQuantile to break, since this.sorted() assumes that this.stat_sorted is still up to date. 

This can be fixed very simply by adding a function like

    this.resetStatistics = function() {
		this.stat_sorted	= null;
		this.stat_mean 	= null;
		this.stat_median 	= null;
		this.stat_sum 		= null;
		this.stat_max 		= null;
		this.stat_min 		= null;
		this.stat_pop 		= null;
		this.stat_variance	= null;
		this.stat_stddev	= null;
		this.stat_cov		= null;
    }

that would be called after setting the new serie in setSerie.

i.e.

    this.setSerie = function(a) {
        this.log('Setting serie (' + a.length + ') : ' + a.join());
	
		this.serie = Array() // init empty array to prevent bug when calling classification after another with less items (sample getQuantile(6) and getQuantile(4))
		this.serie = a;
		
		//reset statistics after changing serie
		this.resetStatistics();
		
		this.setPrecision();
    }

**Comment by simogeo** [comment]
Thanks ! I updated the library and made a new release : https://github.com/simogeo/geostats/releases/tag/v1.5.0

**Comment by daniel-zillion** [comment]
No problem! Thanks for the quick response.
