### ISSUE TITLE
classify issue

### ISSUE THREAD

**Issue by ghazal-karami** [simogeo/geostats#31]
Hi,

We get classify issue when the number of classes (user selects) is equal or greater than the number of values that are going to be classified.

I can give you examples if it is not clear.

Regards,
Ghazal

**Comment by simogeo** [comment]
should tests be handled by the library itself or by the developer ? What do you think ?

**Comment by ghazal-karami** [comment]
shouldn't the library work for at least equal number of classes and number of values?
It is not testing actually. The question is about the   logic behind the jenks!

**Comment by simogeo** [comment]
Is this happening only with Jenks or even with other classification methods ? 

>  The question is about the logic behind the jenks!
I understand and I'm willing to enhance the library, of course but I 'm not sure to agree with this ... in the sense there is no logic applying 4 classes on 4 values serie ...

If you want to provide a pull request, you are welcome.
