### ISSUE TITLE
Typo bug converting string to float

### ISSUE THREAD

**Issue by UhtredBosch** [simogeo/geostats#32]
Hi and thanks very much for your very useful library.

I was getting at an error something to do with 'a[i].toFixed is not a function' and I found a typo in line 240 of geostats.js.

Currently it's 

b[i] = parseFloat(a[i].toFixed(this.precision));

and changing that to 

b[i] = parseFloat(a[i]).toFixed(this.precision);

got rid of the error.

Again Thanks!

**Comment by simogeo** [comment]
Thanks to you to pointing this out. Corrected, now.

Is there any online implementation I can add on the [wiki page](https://github.com/simogeo/geostats/wiki) ? thanks again !
