### ISSUE TITLE
Uncaught RangeError when using numbers with great precision in Chromium

### ISSUE THREAD

**Issue by mthh** [simogeo/geostats#34]
Hi,

When I have an array of numbers with a great precision and try to initialize a `geostats` object I get `Uncaught RangeError: toFixed() digits argument must be between 0 and 20` when using chromium/chrome, although it works fine in Firefox.
Is it a misuse from me ? Or something to be fixed ?

### How to reproduce it :
```
> arr = [0.00000123456789123456789, 0.00000123456789123456789, 0.123, 0.156]
Array [ 0.0000012345678912345679, 0.0000012345678912345679, 0.123, 0.156 ]
> s = new geostats(arr)
geostats.js:240 Uncaught RangeError: toFixed() digits argument must be between 0 and 20
```
### What is happening :
In `geostats.js`  using chormium: 
*(line 211)* `var precision = (this.serie[i] + "").split(".")[1].length;` set `this.precision` to 22, which is too high to be used *(line 240)* in `b[i] = parseFloat(a[i]).toFixed(this.precision);`
(its gives the same precision, 22, in Firefox but the `.toFixed()` method wont complain before a precision of 101)

### How to fix it ?
Maybe by truncating the precision to 20 when necessary ? Or in any case ? (it was gonna be truncated to 22) and according to [Mozilla Developer Network](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toFixed), the arguments of `toFixed()` ...
> ... may be a value between 0 and 20, inclusive, and implementations may optionally support a larger range of values.

I don't know nor if that should be handled by `geostats` neither if there is a clean way to check that before encountering the error but it's still possible to reduce the precision at this point...:
```
@@ -237,7 +237,15 @@ var geostats = function(a) {
 		for (var i = 0; i < a.length; i++) {
 			// check if the given value is a number
 			if (isNumber(a[i])) {
-				b[i] = parseFloat(a[i]).toFixed(this.precision);
+				try {
+					b[i] = parseFloat(a[i]).toFixed(this.precision);
+				} catch (e) {
+					if(this.precision > 20) {
+						this.precision = 20;
+						b[i] = parseFloat(a[i]).toFixed(this.precision);
+					} else
+						throw e;
+				}
 			} else {
 				b[i] = a[i];
 			}
```

Cheers!

**Comment by simogeo** [comment]
Well spotted. I've never worked with such precision on decimal numbers.

I added the proposed patch to current code

**Comment by simogeo** [comment]
Thanks

**Comment by mthh** [comment]
Thanks too!

**Comment by mthh** [comment]
Sorry to come back on this, but I'm a bit uncomfortable with my proposed fix. As one might have expected, the `try ... catch` located in the loop seems to hurt performances...

A similar fix with a slightly different approach could be to test it only once before the loop with something like : 
```
@@ -234,19 +234,16 @@ var geostats = function(a) {
 		
 		var b = new Array();
 		
+		try {
+			1.1.toFixed(this.precision);
+		} catch (e) {
+			if(this.precision > 20) this.precision = 20;
+			else throw e;
+		}
 		for (var i = 0; i < a.length; i++) {
 			// check if the given value is a number
 			if (isNumber(a[i])) {
-				try {
-					b[i] = parseFloat(a[i]).toFixed(this.precision);
-				} catch (e) {
-					if(this.precision > 20) {
-						this.precision = 20;
-						b[i] = parseFloat(a[i]).toFixed(this.precision);
-					} else {
-						throw e;
-					}
-				}
+				b[i] = parseFloat(a[i]).toFixed(this.precision);
 			} else {
 				b[i] = a[i];
 			}
```
Cheers,
mthh

**Comment by simogeo** [comment]
You're right it was a bit dirty. 
I propose to handle this case in setPrecision() method itself - see next commit 

BTW, what is this syntax ? `1.1.toFixed(this.precision);` (1.1) I've never seen this before, I'm curious ?

**Comment by simogeo** [comment]
see 42639e0458f30300512ce08e9c40c6d8917d3e73

**Comment by simogeo** [comment]
Not tested. Any feedback is welcome

**Comment by mthh** [comment]
I guess your choice make more sense, as the behavior is now more consistent between browsers.

Concerning `1.1.toFixed(this.precision);` it was just a quick way to trigger the `toFixed()` method on a float `Number` to test it with `this.precision` (so 1.1 was a random choice, as whatever the length of this Number, chrome was gonna throw an exception if the precision argument is superior to 20).

**Comment by simogeo** [comment]
> it was just a quick way to trigger the toFixed() method on a float Number to test it with this.precision (so 1.1 was a random choice, as whatever the length of this Number, chrome was gonna throw an exception if the precision argument is superior to 20).

Got it.
