### ISSUE TITLE
License

### ISSUE THREAD

**Issue by dmfenton** [simogeo/geostats#37]
How is this project licensed? I'm interested making use of this project but cannot due so unless it's under some kind of license like MIT or Apache.

**Comment by simogeo** [comment]
It is released under MIT LIcence. See end of [readme file](https://github.com/simogeo/geostats/blob/master/readme.md) and [source code itself](https://github.com/simogeo/geostats/blob/master/lib/geostats.js)

**Comment by dmfenton** [comment]
My apologies. It would have been helpful if you included a `License` file as that's where I look first.
