### ISSUE TITLE
Samples not working?

### ISSUE THREAD

**Issue by bladeoflight16** [simogeo/geostats#39]
On https://www.intermezzo-coop.eu/mapping/geostats/, the samples just show up as blank for me:

![blank sample map](https://user-images.githubusercontent.com/1159076/39071889-afec0dd0-44b6-11e8-972f-756767d52355.png)

I've tested in Firefox, Chrome, and IE. The [shapefile to geojson sample](https://www.intermezzo-coop.eu/mapping/geostats/sample_shp.html) works, though.

**Comment by simogeo** [comment]
ohhh, thanks for reporting. This is due to HTTPS protocol forcing

It should be ok now. Please see : https://www.intermezzo-coop.eu/mapping/geostats/
