### ISSUE TITLE
Numeric separators?

### ISSUE THREAD

**Issue by kerstin** [simogeo/geostats#41]
Geostats does not currently support numeric separators in any form, does it? I was wondering for a way to get `getHtmlLegend` to output large numbers with thousands separators but I'm guessing I'd have to rewrite the function to make that happen?

(Just discovered [this](http://2ality.com/2018/02/numeric-separators.html), which suggests this'll be a feature in V8, but was wondering in general.)

**Comment by simogeo** [comment]
Hi @kerstin, looking at [codesource](https://github.com/simogeo/geostats/blob/master/lib/geostats.js#L1054), you will see that `getHtmlLegend()` takes a callback function which applies to bounds.

You should then be able to call your own function to handle separtaors, or use libraries as [numerals.js](http://numeraljs.com/).

```
	/**
	 * Return an html legend
	 * colors : specify an array of color (hexadecimal values)
	 * legend :  specify a text input for the legend. By default, just displays 'legend'
	 * counter : if not null, display counter value
	 * callback : if not null, callback function applied on legend boundaries
	 * mode : 	null, 'default', 'distinct', 'discontinuous' : 
	 * order : 	null, 'ASC', 'DESC'
	 */
```

Hope it answers your need.

**Comment by kerstin** [comment]
@simogeo Thank you! This was indeed exactly what I was looking for. Would it make sense to include a summary of the options in the README? I could put something together and send a PR (probably not right away, but within the next 1-2 weeks or so).

**Comment by simogeo** [comment]
You're mot welcome to do it ! 
I'm waiting for your PR. Thanks in advance @kerstin !
