### ISSUE TITLE
NPM Usage

### ISSUE THREAD

**Issue by KaiVolland** [simogeo/geostats#43]
Hey,

I'm really interested in using this lib for the [GeoStyler](https://terrestris.github.io/geostyler/) but the last release on NPM was 3 years ago.

Are there any plans to reactivate the NPM package or do i have to download the lib from github and include it 'manual'.

BTW: The minified version is currently broken (0 bytes).

**Comment by simogeo** [comment]
Hi @KaiVolland thanks for reporting broken minified file. It is supposed to be fixed.
I have created a  1.7.0 release.

I'm now dealing with npm - which I'm not very familiar.
I updated all security / auth stuff in NPM settings and ran "update package settings". Still, it seems to be blocked on 1.5.0 version. Any help would be very useful. Do you have any idea ?

Also interested by your geostyle project. The demo is not available right now.

**Comment by simogeo** [comment]
@KaiVolland : I've been struggling but finally I manage to update npm package : https://www.npmjs.com/package/geostats

Enjoy
