### ISSUE TITLE
npm import issue

### ISSUE THREAD

**Issue by liqian7** [simogeo/geostats#44]
When I import geostats in npm , I encountered an error when calling the ‘’getClassJenks‘’ method.
error： Uncaught (in promise) ReferenceError: dataList is not defined.
![image](https://user-images.githubusercontent.com/35757238/50670570-7bd6c900-1007-11e9-81b8-1d569ec17a52.png)

**Comment by simogeo** [comment]
Have you tried using unminified version ?

**Comment by simogeo** [comment]
can I close that ?
