### ISSUE TITLE
using with typescript

### ISSUE THREAD

**Issue by bpiasecki** [simogeo/geostats#51]
What i'm trying to do is to import this package into Angular 8 project with Typescript. Unfortunatelly im getting errors "i is not defined" or "round is not defined", both of variables in all use cases are not declared in source code. 
Please fix it by adding 'var' keyword before every 'i' in loops and before round object declaration

**Comment by simogeo** [comment]
thanks for reporting @bpiasecki, I'll try to fix this today and I ask you to do some tests

**Comment by simogeo** [comment]
Can you please test now and let me know ?

**Comment by bpiasecki** [comment]
Thanks for fast response :)  I can't run app right now but i can see that there're still missing declarations of 'datalist' objects in getClassJenks and getClassJenks2.

BTW, awesome work with this library!

**Comment by simogeo** [comment]
Thanks !

Here we go : 504316af8c9e25655289417dab97bd7af28b5175
https://github.com/simogeo/geostats/commit/504316af8c9e25655289417dab97bd7af28b5175

**Comment by hawklorry** [comment]
Is this version published on npm yet? It seems the latest version is still 1.8.0. I encounter same issue in my Angular application.

**Comment by simogeo** [comment]
@hawklorry : Should be ok, now !

**Comment by hawklorry** [comment]
It works. Thanks for the quick response.

**Comment by simogeo** [comment]
My pleasure !
