### ISSUE TITLE
Difference in results between getClassJenks and getClassJenks2

### ISSUE THREAD

**Issue by mthh** [simogeo/geostats#52]
By doing some tests I saw that we get different results depending on the use of `getClassJenks` or `getClassJenks2` (the old version). Is this normal?

I've dropped two sets of values to reproduce my example: https://gist.github.com/mthh/bda5150a1389733c9709a1e1f5b4e756

With data from file a.json :
```js
g = new geostats(values)
g.getClassJenks(7)
// Output:
// [0.0028109620325267315, 1.2488291063345969, 2.6667816913686693, 4.124441018793732, 5.528719199355692, 6.937670034822077, 8.41798685491085, 9.997982932254672]
g.getClassJenks2(7)
// Output:
// [0.0028109620325267315, 1.2488291063345969, 2.6667816913686693, 4.124441018793732, 5.528719199355692, 6.937670034822077, 8.431752701289952, 9.997982932254672]
```

With data from file b.json :
```js
g = new geostats(values)
g.getClassJenks(7)
// Output:
// [0, 0, 10435, 11643, 12476, 13336, 16073, 27125]
g.getClassJenks2(7)
// Output:
// [0, 0, 10435, 11643, 12476, 13337, 16116, 27125]
```

In both cases it is the penultimate value which is different.

**Comment by simogeo** [comment]
hi @mthh, I've noticed myself the different results and that's precisely why the library still provides both methods.

Is there a wrong / right classification ? At that point, I'm not sure ... but it would be nice if you could investigate a bit more.

Could you tell me how many values get your statistical series and how much fall into which classes.

You can just display [counter](https://github.com/simogeo/geostats/blob/master/lib/geostats.js#L1230) when calling `getHtmlLegend(colors, legend, counter, callback, mode, order) ` to know that and compare both classification. 
See online sample : https://www.intermezzo-coop.eu/mapping/geostats/#sample-9

Pleas let me know !

**Comment by mthh** [comment]
Well, I agree with "Is there a wrong / right classification ?" !
On the other hand, it seems that the code of `getClassJenks` implements strictly the same algorithm as `getClassJenks2` (with clearer variable names, and a slightly more efficient implementation).

After reviewing the implementation of `getClassJenks` and `getClassJenks2` I can only see a difference in logic at this line: 
https://github.com/simogeo/geostats/blob/master/lib/geostats.js#L1067

In the implementation of `getClassJenks2` we have `k = dataList.length` and in `getClassJenks` we have `k = dataList.length - 1`.
I'm not saying either one is *correct*. But if we modify `getClassJenks` to have `k = dataList.length` on line 1067, then both functions give the same result.

I will do what you advise me in your previous post and keep you informed.

**Comment by simogeo** [comment]
@mthh : quickly .... with your series. See counter values on right side


**A serie :** 
![image](https://user-images.githubusercontent.com/154323/81913213-f0dcea00-95cf-11ea-9694-34eba2047c94.png)

One value only is passing from the penultimate to the ultimate class here.

**B serie :**
![image](https://user-images.githubusercontent.com/154323/81913935-ee2ec480-95d0-11ea-96fc-668352b26f03.png)

And some more values here. I guess, this is because some are multiples. For example `13337` value can be observed 8 times in the serie. 
Let you investigate a bit more !
