### ISSUE TITLE
Jenks breaks error when data.length is less than nbClass

### ISSUE THREAD

**Issue by JoeWDavies** [simogeo/geostats#57]
For example:

If my data is 80,70,1 and I request Jenks breaks with 5 classes - it will throw:

Cannot read property '2' of undefined
    at geostats.getClassJenks (geostats.js:1079)

**Comment by moismailzai** [comment]
I can confirm this behavior on version 1.8.0.

**Comment by simogeo** [comment]
thanks for reporting, please try current master version 
See https://github.com/simogeo/geostats/commit/fb16702cc1d86ce125b810e86e069813fbd35835
