### ISSUE TITLE
Unnecessarily Large NPM Package Due to Extraneous OpenLayers Directory

### ISSUE THREAD

**Issue by sairus2k** [simogeo/geostats#62]
**Description:**

I have noticed that the `geostats` npm package size is surprisingly large, at about 63 MB. Upon investigating, it seems this is due to a directory called `OpenLayers` that is not actually present in the GitHub repository. This unaccounted space usage could potentially create storage and deployment inefficiencies for users of the package.

**Steps to Reproduce:**

1. Install the `geostats` package via npm with `npm install geostats`

2. Check the disk usage of the installed package with `du -sh node_modules/geostats` (on Unix-like systems) or equivalent commands on other systems
3. Navigate into the installed `geostats` directory in `node_modules` and observe the `OpenLayers` directory.

**Expected Behavior:**

The npm package size should be more or less similar to the repository size, considering only the necessary files for the library to function.

**Actual Behavior:**

The npm package size is much larger than the GitHub repository due to an extraneous `OpenLayers` directory.

**Comment by simogeo** [comment]
hi @sairus2k : thanks for reporting. Should be fine now : https://www.npmjs.com/package/geostats
